### ISSUE TITLE
这个judge用的是什么沙盒

### ISSUE THREAD

**Issue by zhuqinggang** [syzoj/judge-v3#2]
RT，是不是judge2的sandbox？不过那个judge2的下载链接挂了
求解
还有那个runner-shared-config怎么配置
要是能有详细的部署教程就更好了

**Comment by t123yh** [comment]
你好，
部分说明可以参见这里 https://blog.t123yh.xyz:2/index.php/archives/236
详细配置可以联系我，我给你一个搭建好的示例。
