### ISSUE TITLE
是否可以考虑做个docker镜像？

### ISSUE THREAD

**Issue by fearlessxjdx** [syzoj/judge-v3#3]
web端一次就搭成功了，judge搭了一天都没成功...说明文档又有点少。能否做个docker镜像？或者提供下配置说明
那个demo我看到了，但是按那个配置npm install总是报错。现在正在尝试按照版本一模一样的组件下源码编译，但是这样的配置也太麻烦了点吧......

**Comment by t123yh** [comment]
您好，

我们已经注意到 SYZOJ 难以搭建。我们将在近期（高考后）重构整个 SYZOJ，新版本应该会提供更丰富的功能，也更加容易搭建。我们不推荐在近期搭建 SYZOJ，建议您等候重构后的版本。

2018年6月2日 下午6:39，fearlessxjdx <notifications@github.com>写道：

web端一次就搭成功了，judge搭了一天都没成功...说明文档又有点少。能否做个docker镜像？或者提供下配置说明
那个demo我看到了，但是按那个配置npm install总是报错。现在正在尝试按照版本一模一样的组件下源码编译，但是这样的配置也太麻烦了点吧......

―

**Comment by jyeric** [comment]
@t123yh 好像这里面有docker版的syzoj：https://github.com/hewenyang/syzoj-docker

**Comment by jyeric** [comment]
@fearlessxjdx
