### ISSUE TITLE
出现无论如何都ac的情况

### ISSUE THREAD

**Issue by qwe7002** [syzoj/judge-v3#5]
使用master版本部署，发现即使运行退出代码为1的时候，也会AC。只有部分测试点提示答案错误

**Comment by qwe7002** [comment]
![54E0318C42E57117F65456DE5C5E6E9B.jpg](https://i.loli.net/2018/09/19/5ba1293dedf50.jpg)

**Comment by Menci** [comment]
答案文件末尾是不是没有换行？可能是因为沙箱环境中的 `diff` 有 bug，你进去更新一下试试

**Comment by qwe7002** [comment]
是的，文件末尾没有换行。这个问题我有空更新一下看看
